using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;

public class LoadOpenWorld : MonoBehaviour
{
    private KeyCode loadMeToOpWo  = KeyCode.Mouse0;

    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        ActionToLoadOpWo();
    }

    private void ActionToLoadOpWo()
    {
        if (Input.GetKeyDown(loadMeToOpWo))
        {
            SceneManager.LoadScene(1);
        }
    }
}
//https://www.youtube.com/watch?v=ztJPnBpae_0&t=470s

