using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using TMPro;
using UnityEngine.UIElements;

public class OnPlayerDeath : MonoBehaviour
{
    [SerializeField] private UnityEngine.UI.Image DeathScreen;
    [SerializeField] private TMP_Text Score;
    [SerializeField] private TMP_Text Highscore;
    [SerializeField] private TMP_Text RoundCounter;
    [SerializeField] private TMP_Text Verbleibend;
    // Start is called before the first frame update

    public void onDeathUI()
    {
        DeathScreen.gameObject.SetActive(true);
        Score.gameObject.SetActive(false);
        Highscore.gameObject.SetActive(false);
        RoundCounter.gameObject.SetActive(false);
        Verbleibend.gameObject.SetActive(false);
    }
}
